# Generated by Django 5.2.1 on 2025-06-09 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='title',
            new_name='school_name',
        ),
    ]
