# Generated by Django 5.2.1 on 2025-06-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='company_name',
            field=models.CharField(default='Unknown Company', max_length=200),
        ),
    ]
