# Generated by Django 5.2.1 on 2025-06-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_workexperience_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
